apiVersion: v1
kind: ConfigMap
metadata:
  name: thehive-config
data:
  application.conf: |-
    play.http.secret.key="YouNeedToChangeThisKey"
    db {
    provider: janusgraph
    janusgraph {
        storage {
        backend: cql
        hostname: ["cassandra"]
        cql {
            cluster-name: thp       # cluster name
            keyspace: thehive           # name of the keyspace
            read-consistency-level: ONE
            write-consistency-level: ONE
        }
        }
    }
    }
    storage {
    provider: localfs
    localfs.directory: /opt/data
    }
  logback.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration debug="false">

        <conversionRule conversionWord="coloredLevel"
            converterClass="play.api.libs.logback.ColoredLevel" />

        <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>${application.home:-.}/logs/application.log</file>
            <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
                <fileNamePattern>${application.home:-.}/logs/application.%i.log.zip</fileNamePattern>
                <minIndex>1</minIndex>
                <maxIndex>10</maxIndex>
            </rollingPolicy>
            <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
                <maxFileSize>10MB</maxFileSize>
            </triggeringPolicy>
            <encoder>
                <pattern>%date [%level] from %logger in %thread - %message%n%xException</pattern>
            </encoder>
        </appender>

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%coloredLevel %logger{15} - %message%n%xException{10}
                </pattern>
            </encoder>
        </appender>

        <appender name="ASYNCFILE" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="FILE" />
        </appender>

        <appender name="ASYNCSTDOUT" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="STDOUT" />
        </appender>

        <logger name="play" level="INFO" />
        <root level="INFO">
            <appender-ref ref="ASYNCFILE" />
            <appender-ref ref="ASYNCSTDOUT" />
        </root>

    </configuration>
    

